function dpDGm = LegJac_pDGm(CDG,DG,theta1,theta2)
%LegJac_pDGm
%    dpDGm = LegJac_pDGm(CDG,DG,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-May-2022 16:15:50

t2 = CDG+theta1+theta2;
dpDGm = reshape([(DG.*cos(t2))./2.0,(DG.*sin(t2))./2.0,0.0,0.0],[2,2]);
