function dpH_pj = LegJac_PJ(AC,BE,CDG,DG,FG,FGH,GH,theta1,theta2)
%LegJac_PJ
%    dpH_pj = LegJac_PJ(AC,BE,CDG,DG,FG,FGH,GH,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    11-May-2022 16:41:43

t2 = FGH+theta1;
t3 = CDG+theta1+theta2;
t4 = -BE;
t5 = 1.0./FG;
t6 = AC+t4;
dpH_pj = reshape([DG.*cos(t3),DG.*sin(t3),-GH.*t5.*t6.*cos(t2),-GH.*t5.*t6.*sin(t2)],[2,2]);
