function dpH_pj = LegJac_PJ(CDG,DG,FGH,GH,theta1,theta2)
%LegJac_PJ
%    dpH_pj = LegJac_PJ(CDG,DG,FGH,GH,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    23-May-2022 18:15:09

t2 = FGH+theta1;
t3 = CDG+theta1+theta2;
dpH_pj = reshape([DG.*cos(t3),DG.*sin(t3),-GH.*cos(t2),-GH.*sin(t2)],[2,2]);
