function dpH = LegJac(AC,CDG,DG,FGH,GH,theta1,theta2)
%LegJac
%    dpH = LegJac(AC,CDG,DG,FGH,GH,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    23-May-2022 18:15:09

t2 = FGH+theta1;
t3 = CDG+theta1+theta2;
t4 = cos(t3);
t5 = sin(t3);
t6 = DG.*t4;
t7 = DG.*t5;
dpH = reshape([t6+AC.*cos(theta1)-GH.*cos(t2),t7+AC.*sin(theta1)-GH.*sin(t2),t6,t7],[2,2]);
