function Jcp = LegJac_Jcp(AC,BE,CDG,DG,FG,FGH,GH,theta2)
%LegJac_Jcp
%    Jcp = LegJac_Jcp(AC,BE,CDG,DG,FG,FGH,GH,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    23-May-2022 17:21:17

t2 = CDG+theta2;
t4 = -BE;
t5 = -FGH;
t3 = sin(t2);
t6 = AC+t4;
t7 = t2+t5;
t8 = sin(t7);
Jcp = reshape([0.0,1.0,-(GH.*t6.*t8)./(AC.*FG.*t3-AC.*GH.*t8+BE.*GH.*t8),(GH.*t6.*(DG.*t8-AC.*sin(FGH)))./(AC.*DG.*FG.*t3-AC.*DG.*GH.*t8+BE.*DG.*GH.*t8)],[2,2]);
